name: Deploy to Dev

on:
  push:
    branches: ["develop"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/next-app .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: DockerHub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/next-app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/next-app
            docker stop next-app || true
            docker rm next-app || true
            docker run -d --restart unless-stopped -p 3000:3000 --name next-app ${{ secrets.DOCKERHUB_USERNAME }}/next-app
            docker image prune -f
